CREATE TABLE inec_tbl_edg_2015(
item text
,prov_insc text
,cant_insc text
,parr_insc text
,anio_insc text
,mes_insc text
,dia_insc text
,fecha_insc text
,nac_fall text
,cod_pais text
,sexo text
,anio_nac text
,mes_nac text
,dia_nac text
,fecha_nac text
,anio_fall text
,mes_fall text
,dia_fall text
,fecha_fall text
,cod_edad text
,edad text
,prov_res text
,area_res text
,est_civil text
,sabe_leer text
,niv_inst text
,etnia text
,lugar_ocur text
,prov_fall text
,cant_fall text
,parr_fall text
,area_fall text
,causa4 text
,causa text
,mort_mat text
,Obser_mort_mat text
,muj_fertil text
,mor_viol text
,lug_viol text
,autopsia text
,cer_por text
,lc1 text
,causa103 text
,causa80 text
,causa67A text
,causa67B text
);


DROP TABLE inec_tbl_edg_2016;
CREATE TABLE inec_tbl_edg_2016(
prov_insc text
,cant_insc text
,parr_insc text
,anio_insc text
,mes_insc text
,dia_insc text
,fecha_insc text
,nac_fall text
,cod_pais text
,sexo text
,anio_nac text
,mes_nac text
,dia_nac text
,fecha_nac text
,anio_fall text
,mes_fall text
,dia_fall text
,fecha_fall text
,cod_edad text
,edad text
,prov_res text
,area_res text
,est_civil text
,sabe_leer text
,niv_inst text
,etnia text
,lugar_ocur text
,prov_fall text
,cant_fall text
,parr_fall text
,area_fall text
,causa4 text
,causa text
,mor_mat text
,obser_mort_mat text
,muj_fertil text
,mor_viol text
,lug_viol text
,autopsia text
,cer_por text
,lc1 text
,causa103 text
,causa80 text
,causa67A text
,causa67B text
);

DROP TABLE inec_tbl_edg_2017;
CREATE TABLE inec_tbl_edg_2017(
prov_insc text
,cant_insc text
,parr_insc text
,anio_insc text
,mes_insc text
,dia_insc text
,fecha_insc text
,nac_fall text
,cod_pais text
,sexo text
,anio_nac text
,mes_nac text
,dia_nac text
,fecha_nac text
,anio_fall text
,mes_fall text
,dia_fall text
,fecha_fall text
,edad text
,cod_edad text
,prov_res text
,area_res text
,est_civil text
,niv_inst text
,sabe_leer text
,etnia text
,lugar_ocur text
,prov_fall text
,cant_fall text
,parr_fall text
,area_fall text
,causa4 text
,muj_fertil text
,mor_viol text
,lug_viol text
,autopsia text
,cer_por text
,lc1 text
,causa text
,mor_mat text
,causa103 text
,causa80 text
,causa67A text
,causa67B text
);

DROP TABLE inec_tbl_edg_2018;
CREATE TABLE inec_tbl_edg_2018(
numeracion text
,prov_insc text
,cant_insc text
,parr_insc text
,fecha_insc text
,anio_insc text
,mes_insc text
,dia_insc text
,nac_fall text
,cod_pais text
,sexo text
,fecha_nac text
,anio_nac text
,mes_nac text
,dia_nac text
,fecha_fall text
,anio_fall text
,mes_fall text
,dia_fall text
,cod_edad text
,edad text
,prov_res text
,area_res text
,est_civil text
,niv_inst text
,sabe_leer text
,etnia text
,lugar_ocur text
,prov_fall text
,cant_fall text
,parr_fall text
,area_fall text
,cer_por text
,muj_fertil text
,mor_viol text
,lug_viol text
,autopsia text
,causa4 text
,causa text
,lc1 text
,causa103 text
,causa80 text
,causa67A text
,causa67B text
,residente text
);

DROP TABLE inec_tbl_edg_2019;
CREATE TABLE inec_tbl_edg_2019(
numeracion text
,prov_insc text
,cant_insc text
,parr_insc text
,anio_insc text
,mes_insc text
,dia_insc text
,fecha_insc text
,nac_fall text
,cod_pais text
,sexo text
,anio_nac text
,mes_nac text
,dia_nac text
,fecha_nac text
,anio_fall text
,mes_fall text
,dia_fall text
,fecha_fall text
,cod_edad text
,edad text
,prov_res text
,sabe_leer text
,etnia text
,lugar_ocur text
,prov_fall text
,cant_fall text
,parr_fall text
,muj_fertil text
,mor_viol text
,lug_viol text
,autopsia text
,causa4 text
,cer_por text
,area_fall text
,area_res text
,est_civil text
,niv_inst text
,residente text
,causa text
,lc1 text
,causa103 text
,causa80 text
,causa67A text
,causa67B text
);

DROP TABLE inec_tbl_edg_2020;
CREATE TABLE inec_tbl_edg_2020(
numeracion text
,prov_insc text
,cant_insc text
,parr_insc text
,anio_insc text
,mes_insc text
,dia_insc text
,fecha_insc text
,sexo text
,anio_fall text
,mes_fall text
,dia_fall text
,fecha_fall text
,anio_nac text
,mes_nac text
,dia_nac text
,fecha_nac text
,edad text
,cod_edad text
,prov_fall text
,cant_fall text
,parr_fall text
,area_fall text
,nac_fall text
,cod_pais text
,etnia text
,est_civil text
,niv_inst text
,sabe_leer text
,autopsia text
,causa4 text
,lugar_ocur text
,cer_por text
,mor_viol text
,lug_viol text
,prov_res text
,area_res text
,causa text
,lc1 text
,causa103 text
,causa80 text
,causa67A text
,causa67B text
,residente text
);